import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "Absolute Title",
    default: "Default Title",
    template: "%s | Tab Title"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div lang="en">
      <div style={{backgroundColor: 'lightblue', padding: '1rem'}}>
        <p>Header!</p>
      </div>
      <body>{children}</body>
      <div style={{backgroundColor: 'red', padding: '1rem'}}>
        <p>Footer!</p>
      </div>
    </div>
  )
}
